import { StyleSheet } from 'react-native';

import { THEME } from '@/constants/theme';

export const PACK_CANVAS = '#F4F7FB';
const SLATE_LINE = '#E2E8F0';
const SLATE_MUTED = '#64748B';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: PACK_CANVAS,
  },
  scrollContent: {
    paddingHorizontal: THEME.spacing[16],
    paddingTop: THEME.spacing[4],
    paddingBottom: THEME.spacing[20],
    gap: THEME.spacing[10],
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: THEME.spacing[20],
    backgroundColor: PACK_CANVAS,
    gap: THEME.spacing[10],
  },
  heroGradient: {
    borderRadius: 16,
    padding: THEME.spacing[14],
    gap: THEME.spacing[10],
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[10],
  },
  heroIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  heroTitle: {
    fontSize: THEME.typography.size[17],
    fontWeight: THEME.typography.weight.bold as '700',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  heroSubtitle: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.85)',
  },
  heroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  statusDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#6EE7B7',
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: THEME.typography.weight.bold as '700',
    color: '#FFFFFF',
  },
  heroStatText: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.9)',
    fontWeight: THEME.typography.weight.medium as '500',
  },
  progressBlock: {
    gap: 6,
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressLabel: {
    fontSize: 10,
    fontWeight: THEME.typography.weight.semibold as '600',
    color: 'rgba(255,255,255,0.88)',
  },
  progressValue: {
    fontSize: THEME.typography.size[13],
    fontWeight: THEME.typography.weight.bold as '700',
    color: '#FFFFFF',
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.25)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
  },
  callout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing[8],
    paddingVertical: THEME.spacing[10],
    paddingHorizontal: THEME.spacing[12],
    borderRadius: 12,
    borderWidth: 1,
  },
  calloutNext: {
    borderColor: 'rgba(245,158,11,0.35)',
    backgroundColor: '#FFFBEB',
  },
  calloutUpgrade: {
    borderColor: 'rgba(13,148,136,0.3)',
    backgroundColor: '#F0FDFA',
  },
  calloutTitle: {
    fontSize: 11,
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
  },
  calloutBody: {
    marginTop: 2,
    fontSize: THEME.typography.size[12],
    color: SLATE_MUTED,
    lineHeight: 17,
  },
  upgradeLink: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  upgradeLinkText: {
    fontSize: 11,
    fontWeight: THEME.typography.weight.semibold as '600',
    color: '#0D9488',
  },
  servicesBlock: {
    backgroundColor: THEME.colors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    overflow: 'hidden',
  },
  servicesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: THEME.spacing[12],
    paddingVertical: THEME.spacing[10],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLATE_LINE,
    backgroundColor: '#FAFBFC',
  },
  servicesTitle: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
  },
  servicesCount: {
    fontSize: 11,
    color: SLATE_MUTED,
    marginTop: 1,
  },
  applyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: THEME.colors.primary,
  },
  applyBtnDisabled: {
    opacity: 0.45,
  },
  applyBtnText: {
    fontSize: 11,
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.white,
  },
  serviceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[10],
    paddingHorizontal: THEME.spacing[12],
    paddingVertical: THEME.spacing[10],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLATE_LINE,
  },
  serviceRowLast: {
    borderBottomWidth: 0,
  },
  serviceIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  serviceTitle: {
    fontSize: THEME.typography.size[13],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
  },
  serviceMeta: {
    fontSize: 11,
    color: SLATE_MUTED,
    lineHeight: 15,
  },
  requestBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    minWidth: 76,
    alignItems: 'center',
  },
  requestBtnPrimary: {
    borderColor: THEME.colors.primary,
    backgroundColor: 'rgba(15,81,50,0.06)',
  },
  requestBtnDisabled: {
    opacity: 0.5,
  },
  requestBtnText: {
    fontSize: 10,
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
  },
  requestBtnTextPrimary: {
    color: THEME.colors.primary,
  },
  emptyServices: {
    fontSize: THEME.typography.size[12],
    color: SLATE_MUTED,
    textAlign: 'center',
    padding: THEME.spacing[16],
  },
  statePanel: {
    backgroundColor: THEME.colors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    padding: THEME.spacing[20],
    alignItems: 'center',
    gap: THEME.spacing[10],
    width: '100%',
  },
  emptyIconRing: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(13,148,136,0.3)',
    backgroundColor: 'rgba(13,148,136,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: THEME.typography.size[16],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
    textAlign: 'center',
  },
  emptyBody: {
    fontSize: THEME.typography.size[12],
    color: SLATE_MUTED,
    textAlign: 'center',
    lineHeight: 18,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
    paddingHorizontal: THEME.spacing[16],
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: THEME.colors.primary,
  },
  primaryBtnText: {
    fontSize: THEME.typography.size[13],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.white,
  },
  retryBtn: {
    paddingHorizontal: THEME.spacing[16],
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    backgroundColor: THEME.colors.white,
  },
  retryBtnText: {
    fontSize: THEME.typography.size[13],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
  },
  errorText: {
    fontSize: THEME.typography.size[13],
    color: THEME.colors.danger,
    textAlign: 'center',
    lineHeight: 18,
  },
});
