import { Platform, StyleSheet } from 'react-native';

import { THEME } from '@/constants/theme';

export const PACK_CANVAS = '#F0F2F5';
const SLATE_LINE = '#E8ECF1';
const SLATE_MUTED = '#64748B';
const TEXT_PRIMARY = '#0F172A';

const CARD_SHADOW = Platform.select({
  ios: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  android: { elevation: 3 },
  default: {},
});

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: PACK_CANVAS,
  },
  scrollContent: {
    paddingHorizontal: THEME.spacing[16],
    paddingTop: THEME.spacing[12],
    paddingBottom: THEME.spacing[20],
    gap: THEME.spacing[14],
  },
  scrollContentCentered: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: THEME.spacing[20],
    backgroundColor: PACK_CANVAS,
    gap: THEME.spacing[10],
  },
  heroGradient: {
    borderRadius: 20,
    padding: THEME.spacing[16],
    ...CARD_SHADOW,
  },
  heroInner: {
    gap: THEME.spacing[14],
    zIndex: 1,
  },
  heroDecorLayer: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 20,
    overflow: 'hidden',
  },
  heroDecor: {
    position: 'absolute',
    top: -24,
    right: -16,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  heroDecorSmall: {
    position: 'absolute',
    bottom: 8,
    left: -12,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing[12],
  },
  heroIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 6,
    paddingTop: 0,
    paddingRight: THEME.spacing[4],
  },
  heroEyebrow: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: 'rgba(255,255,255,0.72)',
    lineHeight: 16,
  },
  heroTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
    lineHeight: 26,
    ...Platform.select({
      ios: { paddingVertical: 1 },
      default: {},
    }),
  },
  heroSubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.88)',
    fontWeight: '500',
    lineHeight: 18,
  },
  heroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#6EE7B7',
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: -0.1,
  },
  heroStatText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '600',
  },
  progressBlock: {
    gap: THEME.spacing[8],
    paddingBottom: 2,
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
    letterSpacing: -0.1,
    lineHeight: 16,
  },
  progressValue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
    lineHeight: 20,
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.22)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
  },
  statsRow: {
    flexDirection: 'row',
    gap: THEME.spacing[10],
  },
  statCard: {
    flex: 1,
    backgroundColor: THEME.colors.white,
    borderRadius: 14,
    paddingVertical: THEME.spacing[12],
    paddingHorizontal: THEME.spacing[10],
    alignItems: 'center',
    gap: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: SLATE_LINE,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
      },
      android: { elevation: 1 },
      default: {},
    }),
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: SLATE_MUTED,
    textAlign: 'center',
  },
  callout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing[12],
    paddingVertical: THEME.spacing[14],
    paddingHorizontal: THEME.spacing[14],
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    backgroundColor: THEME.colors.white,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
      },
      android: { elevation: 1 },
      default: {},
    }),
  },
  calloutNext: {
    borderColor: 'rgba(245,158,11,0.25)',
    borderLeftWidth: 3,
    borderLeftColor: '#F59E0B',
  },
  calloutUpgrade: {
    borderColor: 'rgba(13,148,136,0.22)',
    borderLeftWidth: 3,
    borderLeftColor: '#0D9488',
  },
  calloutIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calloutIconWrapNext: {
    backgroundColor: '#FFFBEB',
  },
  calloutIconWrapUpgrade: {
    backgroundColor: '#F0FDFA',
  },
  calloutContent: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  calloutTitle: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: '#B45309',
  },
  calloutBody: {
    fontSize: 14,
    color: TEXT_PRIMARY,
    lineHeight: 20,
    fontWeight: '500',
    letterSpacing: -0.2,
  },
  upgradeLink: {
    marginTop: THEME.spacing[8],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  upgradeLinkText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0D9488',
  },
  servicesBlock: {
    backgroundColor: THEME.colors.white,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: SLATE_LINE,
    overflow: 'hidden',
    ...CARD_SHADOW,
  },
  servicesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: THEME.spacing[16],
    paddingVertical: THEME.spacing[14],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLATE_LINE,
  },
  servicesTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: TEXT_PRIMARY,
    letterSpacing: -0.3,
  },
  servicesCount: {
    fontSize: 13,
    color: SLATE_MUTED,
    marginTop: 2,
    fontWeight: '500',
  },
  serviceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[12],
    paddingHorizontal: THEME.spacing[14],
    paddingVertical: THEME.spacing[14],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLATE_LINE,
    minHeight: 76,
  },
  serviceRowLast: {
    borderBottomWidth: 0,
  },
  serviceStep: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  serviceStepText: {
    fontSize: 13,
    fontWeight: '800',
  },
  serviceText: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  serviceTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: TEXT_PRIMARY,
    letterSpacing: -0.2,
    lineHeight: 20,
  },
  statusPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: -0.1,
  },
  serviceRemarks: {
    fontSize: 12,
    color: SLATE_MUTED,
    lineHeight: 16,
  },
  requestBtn: {
    minHeight: 36,
    minWidth: 84,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  requestBtnPrimary: {
    borderColor: THEME.colors.primary,
    backgroundColor: 'rgba(15,81,50,0.08)',
  },
  requestBtnDisabled: {
    opacity: 0.55,
  },
  requestBtnPressed: {
    opacity: 0.88,
  },
  requestBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: SLATE_MUTED,
    letterSpacing: -0.1,
  },
  requestBtnTextPrimary: {
    color: THEME.colors.primary,
  },
  emptyServices: {
    fontSize: 14,
    color: SLATE_MUTED,
    textAlign: 'center',
    padding: THEME.spacing[24],
    lineHeight: 20,
  },
  statePanel: {
    backgroundColor: THEME.colors.white,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: SLATE_LINE,
    padding: THEME.spacing[24],
    alignItems: 'center',
    gap: THEME.spacing[12],
    width: '100%',
    ...CARD_SHADOW,
  },
  emptyIconRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(13,148,136,0.28)',
    backgroundColor: 'rgba(13,148,136,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: TEXT_PRIMARY,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  emptyBody: {
    fontSize: 14,
    color: SLATE_MUTED,
    textAlign: 'center',
    lineHeight: 21,
    maxWidth: 280,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: THEME.spacing[4],
    paddingHorizontal: THEME.spacing[20],
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: THEME.colors.primary,
    minHeight: 44,
  },
  primaryBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: THEME.colors.white,
  },
  retryBtn: {
    paddingHorizontal: THEME.spacing[20],
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    backgroundColor: THEME.colors.white,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
  errorText: {
    fontSize: 14,
    color: THEME.colors.danger,
    textAlign: 'center',
    lineHeight: 21,
  },
});
