import { StyleSheet } from 'react-native';

export const processColors = {
  primary: '#7C3AED',
  secondary: '#A855F7',
  bg: '#F5F3FF',
  card: '#FFFFFF',
  text: '#0F172A',
  muted: '#64748B',
  border: '#E2E8F0',
  line: '#DDD6FE',
  success: '#10B981',
  white: '#FFFFFF',
} as const;

export const processGradients = {
  badge: ['#8B5CF6', '#7C3AED'] as const,
  stepCircle: ['#A855F7', '#7C3AED'] as const,
  stepCard: ['#FFFFFF', '#FAF5FF'] as const,
} as const;

export const styles = StyleSheet.create({
  container: {
    backgroundColor: processColors.bg,
    borderRadius: 32,
    padding: 22,
    overflow: 'hidden',
  },
  decorCircleTop: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: processColors.line,
    opacity: 0.4,
  },
  decorCircleBottom: {
    position: 'absolute',
    bottom: -60,
    left: -50,
    width: 160,
    height: 160,
    borderRadius: 999,
    backgroundColor: '#E9D5FF',
    opacity: 0.3,
  },
  header: {
    marginBottom: 28,
  },
  badgeGradient: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    marginBottom: 18,
  },
  badgeText: {
    color: processColors.white,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  title: {
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '800',
    color: processColors.text,
  },
  titleHighlight: {
    color: processColors.primary,
  },
  subtitle: {
    marginTop: 12,
    fontSize: 15,
    lineHeight: 24,
    color: processColors.muted,
  },
  timelineConnector: {
    position: 'absolute',
    left: 22,
    top: 56,
    width: 2,
    height: 72,
    backgroundColor: processColors.line,
  },
  stepWrapper: {
    marginBottom: 14,
  },
  stepWrapperLast: {
    marginBottom: 0,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  stepCircleGradient: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: processColors.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  stepCardPressable: {
    flex: 1,
    marginLeft: 12,
  },
  stepCardGradient: {
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E9D5FF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  stepCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  stepPill: {
    backgroundColor: '#F3E8FF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  stepPillText: {
    color: processColors.primary,
    fontSize: 11,
    fontWeight: '700',
  },
  stepDurationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepDurationText: {
    marginLeft: 4,
    fontSize: 11,
    color: processColors.muted,
    fontWeight: '600',
  },
  stepTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: processColors.text,
    marginBottom: 4,
  },
  stepDescription: {
    fontSize: 13,
    lineHeight: 20,
    color: processColors.muted,
  },
  stepFooterRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: processColors.success,
  },
  stepStatusText: {
    marginLeft: 6,
    color: processColors.success,
    fontWeight: '700',
    fontSize: 12,
  },
  scrollContent: {
    paddingBottom: 8,
  },
  footer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 28,
  },
  footerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: processColors.white,
    borderWidth: 1,
    borderColor: processColors.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginRight: 10,
    marginBottom: 10,
  },
  footerBadgeText: {
    marginLeft: 8,
    fontSize: 13,
    fontWeight: '600',
    color: processColors.text,
  },
});
