import { StyleSheet } from 'react-native';

import { THEME } from '@/constants/theme';

export const BOOKINGS_CANVAS = '#F4F7FB';
const SLATE_LINE = '#E2E8F0';
const SLATE_MUTED = '#64748B';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: BOOKINGS_CANVAS,
  },
  scrollContent: {
    paddingHorizontal: THEME.spacing[16],
    paddingTop: THEME.spacing[4],
    paddingBottom: THEME.spacing[24],
    gap: THEME.spacing[10],
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: THEME.spacing[20],
    backgroundColor: BOOKINGS_CANVAS,
  },
  heroGradient: {
    borderRadius: 16,
    padding: THEME.spacing[14],
    gap: THEME.spacing[10],
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[10],
  },
  heroIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTextBlock: {
    flex: 1,
    gap: 3,
  },
  heroTitle: {
    fontSize: THEME.typography.size[17],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.white,
    letterSpacing: -0.2,
  },
  heroMeta: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.88)',
    lineHeight: 16,
  },
  tabRow: {
    flexDirection: 'row',
    gap: THEME.spacing[8],
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: THEME.spacing[10],
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  tabActive: {
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderColor: 'rgba(255,255,255,0.4)',
  },
  tabText: {
    fontSize: 11,
    fontWeight: THEME.typography.weight.semibold as '600',
    color: 'rgba(255,255,255,0.9)',
  },
  tabTextActive: {
    color: THEME.colors.white,
  },
  tabCount: {
    fontSize: 10,
    fontWeight: THEME.typography.weight.bold as '700',
    color: 'rgba(255,255,255,0.75)',
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    overflow: 'hidden',
  },
  tabCountActive: {
    color: THEME.colors.primary,
    backgroundColor: '#FFFFFF',
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
    backgroundColor: THEME.colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    paddingHorizontal: THEME.spacing[12],
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    fontSize: THEME.typography.size[14],
    color: THEME.colors.textPrimary,
  },
  listBlock: {
    backgroundColor: THEME.colors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    overflow: 'hidden',
  },
  bookingRow: {
    paddingHorizontal: THEME.spacing[12],
    paddingVertical: THEME.spacing[11],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: SLATE_LINE,
    gap: 8,
  },
  bookingRowLast: {
    borderBottomWidth: 0,
  },
  bookingMain: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing[10],
  },
  bookingContent: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  consultantName: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
    flexShrink: 1,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  meta: {
    fontSize: 11,
    color: SLATE_MUTED,
    lineHeight: 15,
    flex: 1,
  },
  amountChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: SLATE_LINE,
  },
  amount: {
    fontSize: 12,
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  statusText: {
    fontSize: 10,
    fontWeight: THEME.typography.weight.bold as '700',
    textTransform: 'capitalize',
  },
  statusPending: { backgroundColor: 'rgba(245,158,11,0.15)' },
  statusPendingText: { color: '#B45309' },
  statusConfirmed: { backgroundColor: 'rgba(5,150,105,0.12)' },
  statusConfirmedText: { color: '#047857' },
  statusCompleted: { backgroundColor: '#F1F5F9' },
  statusCompletedText: { color: '#475569' },
  statusCancelled: { backgroundColor: 'rgba(220,38,38,0.10)' },
  statusCancelledText: { color: '#B91C1C' },
  statusDefault: { backgroundColor: '#F1F5F9' },
  statusDefaultText: { color: '#64748B' },
  callBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: BOOKINGS_CANVAS,
    borderWidth: 1,
    borderColor: SLATE_LINE,
  },
  callBtnText: {
    fontSize: 11,
    fontWeight: THEME.typography.weight.medium as '500',
    color: SLATE_MUTED,
  },
  emptyBlock: {
    padding: THEME.spacing[28],
    alignItems: 'center',
    gap: THEME.spacing[10],
  },
  emptyIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(15,81,50,0.2)',
    backgroundColor: 'rgba(15,81,50,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: THEME.typography.size[15],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
    textAlign: 'center',
  },
  emptyBody: {
    fontSize: THEME.typography.size[12],
    color: SLATE_MUTED,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: THEME.spacing[8],
  },
  linkBtn: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: THEME.spacing[16],
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: THEME.colors.primary,
  },
  linkBtnText: {
    fontSize: THEME.typography.size[13],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.white,
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: THEME.spacing[10],
  },
  pageBtn: {
    paddingHorizontal: THEME.spacing[12],
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: SLATE_LINE,
    backgroundColor: THEME.colors.white,
  },
  pageBtnDisabled: { opacity: 0.45 },
  pageBtnText: {
    fontSize: 11,
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
  },
  pageLabel: {
    fontSize: 11,
    color: SLATE_MUTED,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: THEME.spacing[12],
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(220,38,38,0.25)',
    backgroundColor: 'rgba(254,226,226,0.6)',
  },
  errorText: {
    flex: 1,
    fontSize: THEME.typography.size[12],
    color: THEME.colors.danger,
    lineHeight: 17,
  },
});
