import type { SettingsSectionConfig } from './helpSettings.types';

export const CONSULTANT_HELP_SETTINGS_SECTIONS: SettingsSectionConfig[] = [
  {
    id: 'account',
    title: 'Account',
    rows: [
      {
        id: 'membership',
        icon: 'ribbon-outline',
        iconColor: '#D97706',
        iconBgColor: 'rgba(245,158,11,0.12)',
        title: 'Buy Membership',
        subtitle: 'Manage your subscription plans',
      },
      {
        id: 'myMembership',
        icon: 'card-outline',
        iconColor: '#B45309',
        iconBgColor: 'rgba(180,83,9,0.10)',
        title: 'My Membership',
        subtitle: 'View your active membership plan',
      },
      {
        id: 'profile',
        icon: 'person-outline',
        iconColor: '#2563EB',
        iconBgColor: 'rgba(37,99,235,0.10)',
        title: 'Edit Profile',
        subtitle: 'Update your personal details',
      },
      {
        id: 'notifications',
        icon: 'notifications-outline',
        iconColor: '#0F172A',
        iconBgColor: 'rgba(15,23,42,0.08)',
        title: 'Notifications',
        subtitle: 'Bookings, payouts & alerts',
      },
      {
        id: 'wallet',
        icon: 'wallet-outline',
        iconColor: '#059669',
        iconBgColor: 'rgba(5,150,105,0.10)',
        title: 'My Wallet',
        subtitle: 'Balance, withdrawals & earnings',
      },
      {
        id: 'bizCredits',
        icon: 'sparkles-outline',
        iconColor: '#7C3AED',
        iconBgColor: 'rgba(124,58,237,0.10)',
        title: 'Biz AI credits',
        subtitle: 'Monitor your AI credit usage',
      },
    ],
  },
  {
    id: 'practice',
    title: 'Practice',
    rows: [
      {
        id: 'diagnosticPack',
        icon: 'pulse-outline',
        iconColor: '#0891B2',
        iconBgColor: 'rgba(8,145,178,0.10)',
        title: 'My Diagnostic Pack',
        subtitle: 'View your diagnostic packages',
      },
      {
        id: 'bookings',
        icon: 'calendar-outline',
        iconColor: '#7C3AED',
        iconBgColor: 'rgba(124,58,237,0.10)',
        title: 'Bookings',
        subtitle: 'Track your upcoming bookings',
      },
      {
        id: 'slotTime',
        icon: 'time-outline',
        iconColor: '#16A34A',
        iconBgColor: 'rgba(22,163,74,0.10)',
        title: 'Booking hours',
        subtitle: 'Set when clients can book you',
      },
      {
        id: 'services',
        icon: 'bag-outline',
        iconColor: '#0284C7',
        iconBgColor: 'rgba(2,132,199,0.10)',
        title: 'My Services',
        subtitle: 'Check your active services',
      },
      {
        id: 'locker',
        icon: 'lock-closed-outline',
        iconColor: '#9333EA',
        iconBgColor: 'rgba(147,51,234,0.10)',
        title: 'My Lockers',
        subtitle: 'Securely manage your documents',
      },
      {
        id: 'expertise',
        icon: 'ribbon-outline',
        iconColor: '#DB2777',
        iconBgColor: 'rgba(219,39,119,0.10)',
        title: 'Expertise',
        subtitle: 'Showcase your expertise details',
      },
      {
        id: 'expertVideo',
        icon: 'videocam-outline',
        iconColor: '#EA580C',
        iconBgColor: 'rgba(234,88,12,0.10)',
        title: 'Expert Video',
        subtitle: 'Manage your expert video sessions',
      },
      {
        id: 'review',
        icon: 'star-outline',
        iconColor: '#2563EB',
        iconBgColor: 'rgba(37,99,235,0.10)',
        title: 'Review',
        subtitle: 'Read and manage your reviews',
      },
    ],
  },
  {
    id: 'payouts',
    title: 'Payouts',
    rows: [
      {
        id: 'bankDetails',
        icon: 'business-outline',
        iconColor: '#4F46E5',
        iconBgColor: 'rgba(79,70,229,0.10)',
        title: 'Bank Details',
        subtitle: 'Manage your bank information',
      },
      {
        id: 'withdrawals',
        icon: 'cash-outline',
        iconColor: '#059669',
        iconBgColor: 'rgba(5,150,105,0.10)',
        title: 'Withdrawals',
        subtitle: 'Track your withdrawal requests',
      },
      {
        id: 'transactionHistory',
        icon: 'receipt-outline',
        iconColor: '#64748B',
        iconBgColor: 'rgba(100,116,139,0.12)',
        title: 'Transaction History',
        subtitle: 'View all your transactions',
      },
    ],
  },
];
