import type { SettingsSectionConfig } from './helpSettings.types';

export const USER_HELP_SETTINGS_SECTIONS: SettingsSectionConfig[] = [
  {
    id: 'account',
    title: 'Account',
    rows: [
      {
        id: 'membership',
        icon: 'ribbon-outline',
        iconColor: '#D97706',
        iconBgColor: 'rgba(245,158,11,0.12)',
        title: 'My Membership',
        subtitle: 'Manage your subscription',
      },
      {
        id: 'profile',
        icon: 'person-outline',
        iconColor: '#2563EB',
        iconBgColor: 'rgba(37,99,235,0.10)',
        title: 'My Profile',
        subtitle: 'Personal information',
      },
      {
        id: 'notifications',
        icon: 'notifications-outline',
        iconColor: '#0F172A',
        iconBgColor: 'rgba(15,23,42,0.08)',
        title: 'Notifications',
        subtitle: 'Bookings, payments & alerts',
      },
      {
        id: 'wallet',
        icon: 'wallet-outline',
        iconColor: '#059669',
        iconBgColor: 'rgba(5,150,105,0.10)',
        title: 'Wallet History',
        subtitle: 'Transactions & balance',
      },
      {
        id: 'bizCredits',
        icon: 'sparkles-outline',
        iconColor: '#7C3AED',
        iconBgColor: 'rgba(124,58,237,0.10)',
        title: 'Biz AI credits',
        subtitle: 'Manage AI usage credits',
      },
    ],
  },
  {
    id: 'services',
    title: 'Services & bookings',
    rows: [
      {
        id: 'diagnosticPack',
        icon: 'pulse-outline',
        iconColor: '#0891B2',
        iconBgColor: 'rgba(8,145,178,0.10)',
        title: 'My Diagnostic Pack',
        subtitle: 'View your health packages',
      },
      {
        id: 'bookings',
        icon: 'calendar-outline',
        iconColor: '#7C3AED',
        iconBgColor: 'rgba(124,58,237,0.10)',
        title: 'My Bookings',
        subtitle: 'Upcoming & past bookings',
      },
      {
        id: 'callHistory',
        icon: 'call-outline',
        iconColor: '#16A34A',
        iconBgColor: 'rgba(22,163,74,0.10)',
        title: 'Call History',
        subtitle: 'Recent consultation calls',
      },
      {
        id: 'workshop',
        icon: 'school-outline',
        iconColor: '#DB2777',
        iconBgColor: 'rgba(219,39,119,0.10)',
        title: 'Workshop Bookings',
        subtitle: 'Manage workshop sessions',
      },
      {
        id: 'services',
        icon: 'bag-outline',
        iconColor: '#0284C7',
        iconBgColor: 'rgba(2,132,199,0.10)',
        title: 'My Services',
        subtitle: 'Your active services',
      },
      {
        id: 'edp',
        icon: 'briefcase-outline',
        iconColor: '#EA580C',
        iconBgColor: 'rgba(234,88,12,0.10)',
        title: 'My EDP',
        subtitle: 'Entrepreneurship modules',
      },
      {
        id: 'locker',
        icon: 'lock-closed-outline',
        iconColor: '#9333EA',
        iconBgColor: 'rgba(147,51,234,0.10)',
        title: 'My Locker',
        subtitle: 'Secure document storage',
      },
    ],
  },
  {
    id: 'support',
    title: 'Support',
    rows: [
      {
        id: 'feedback',
        icon: 'chatbubble-ellipses-outline',
        iconColor: '#2563EB',
        iconBgColor: 'rgba(37,99,235,0.10)',
        title: 'User Feedback',
        subtitle: 'Share your experience',
      },
      {
        id: 'guide',
        icon: 'book-outline',
        iconColor: '#4F46E5',
        iconBgColor: 'rgba(79,70,229,0.10)',
        title: 'User Guide',
        subtitle: 'Learn how to use the app',
      },
    ],
  },
];
