import { Platform, StyleSheet } from 'react-native';

export const walletConfirmDialogStyles = StyleSheet.create({
  dialogContent: {
    width: '100%',
    alignItems: 'stretch',
    gap: 0,
  },
  iconWrap: {
    alignSelf: 'center',
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: 'rgba(139, 92, 246, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  iconBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#059669',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryCard: {
    width: '100%',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    marginTop: 6,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  summaryHero: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: 'rgba(139, 92, 246, 0.08)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(139, 92, 246, 0.14)',
    gap: 8,
  },
  packLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#7C3AED',
  },
  packName: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  creditsPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(124, 58, 237, 0.2)',
  },
  creditsPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6D28D9',
  },
  rows: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  rowLabel: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
  },
  rowValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0F172A',
    textAlign: 'right',
    flexShrink: 1,
  },
  rowValueAccent: {
    fontSize: 15,
    fontWeight: '700',
    color: '#059669',
  },
  divider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 2,
  },
  balanceBlock: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 10,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  balanceChip: {
    flex: 1,
    gap: 2,
  },
  balanceChipLabel: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '500',
  },
  balanceChipValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  balanceArrow: {
    width: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footnote: {
    fontSize: 12,
    lineHeight: 17,
    color: '#64748B',
    textAlign: 'center',
    paddingHorizontal: 4,
    marginTop: 2,
  },
  busyWrap: {
    marginTop: 12,
    paddingVertical: 8,
    alignItems: 'center',
    gap: 8,
  },
  busyText: {
    fontSize: 13,
    color: '#059669',
    fontWeight: '600',
  },
  walletTypeTag: {
    alignSelf: 'center',
    marginTop: 2,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
  },
  walletTypeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  },
});
