import { StyleSheet } from 'react-native';

import { THEME } from '@/constants/theme';

export const APPLY_CANVAS = '#F4F7FA';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    gap: 16,
  },
  heroCard: {
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EDF2',
    gap: 4,
  },
  heroLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0B3258',
  },
  appliedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  appliedText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#047857',
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  stepItem: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  stepDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotActive: {
    borderColor: '#0F5132',
    backgroundColor: '#0F5132',
  },
  stepDotDone: {
    borderColor: '#0F5132',
    backgroundColor: '#ECFDF5',
  },
  stepDotText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  stepDotTextActive: {
    color: '#FFFFFF',
  },
  stepDotTextDone: {
    color: '#0F5132',
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#94A3B8',
    textAlign: 'center',
  },
  stepLabelActive: {
    color: '#0F5132',
  },
  stepConnector: {
    position: 'absolute',
    top: 14,
    left: '50%',
    right: '-50%',
    height: 2,
    backgroundColor: '#E2E8F0',
    zIndex: -1,
  },
  sectionCard: {
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EDF2',
    gap: 14,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0B3258',
  },
  sectionHint: {
    fontSize: 13,
    color: '#64748B',
    lineHeight: 18,
  },
  fieldBlock: {
    gap: 8,
  },
  multiAddBtn: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  multiAddText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0B3B66',
  },
  docGroup: {
    gap: 10,
  },
  docGroupTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
  },
  docEmpty: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 17,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
  },
  docRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  docOptionFlex: {
    flex: 1,
  },
  docOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FAFCFE',
  },
  docDeleteBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FECDD3',
    backgroundColor: '#FFF1F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#0F5132',
    marginTop: 4,
  },
  uploadBtnDisabled: {
    backgroundColor: '#94A3B8',
  },
  uploadBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  docSelectionCount: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  docOptionSelected: {
    borderColor: '#0F5132',
    backgroundColor: '#F0FDF4',
  },
  docIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docTextBlock: {
    flex: 1,
    gap: 2,
  },
  docName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0B3258',
  },
  docMeta: {
    fontSize: 11,
    color: '#64748B',
  },
  reviewRoot: {
    gap: 12,
  },
  reviewHeading: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0B3258',
  },
  reviewIntro: {
    fontSize: 14,
    color: '#64748B',
    lineHeight: 20,
  },
  reviewErrorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  reviewErrorBannerText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#B91C1C',
    lineHeight: 18,
  },
  reviewSectionCard: {
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 8,
  },
  reviewSectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0B3258',
  },
  reviewStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reviewStatusText: {
    fontSize: 14,
    fontWeight: '700',
  },
  reviewStatusOk: {
    color: '#047857',
  },
  reviewStatusError: {
    color: '#DC2626',
  },
  reviewIssueList: {
    gap: 6,
    marginTop: 4,
  },
  reviewIssueLine: {
    fontSize: 13,
    fontWeight: '600',
    color: '#DC2626',
    lineHeight: 18,
  },
  reviewHint: {
    fontSize: 13,
    color: '#B45309',
    lineHeight: 18,
  },
  reviewHintOk: {
    fontSize: 13,
    color: '#047857',
    lineHeight: 18,
    fontWeight: '600',
  },
  footerBtnSubmitDisabled: {
    backgroundColor: '#94A3B8',
  },
  footer: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: '#E8EDF2',
    backgroundColor: '#FFFFFF',
  },
  footerBtnOutline: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#0B3B66',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtnOutlineText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0B3B66',
  },
  footerBtnPrimary: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#0F5132',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtnSubmit: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#219653',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtnPrimaryText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  footerSpacer: {
    flex: 1,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APPLY_CANVAS,
  },
  autosaveHint: {
    fontSize: 11,
    color: '#94A3B8',
    textAlign: 'center',
  },
  inputGap: {
    gap: THEME.spacing[12],
  },
});
