import type { NotificationItem } from '../types/notifications.types';

export const CONSULTANT_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'consultant-booking-request',
    section: 'today',
    filterCategory: 'bookings',
    title: 'New Booking Request',
    body: 'New request from Alex for a 1-on-1 session.',
    timeLabel: '2m ago',
    icon: 'person-outline',
    iconColor: '#EA580C',
    iconBgColor: 'rgba(234,88,12,0.12)',
    accentColor: '#EA580C',
    unread: true,
    showActions: true,
    actionTone: 'orange',
  },
  {
    id: 'consultant-incoming-call',
    section: 'today',
    filterCategory: 'bookings',
    title: 'Incoming Call',
    body: 'Incoming call from User Alex.',
    timeLabel: '',
    icon: 'call-outline',
    iconColor: '#EA580C',
    iconBgColor: 'rgba(234,88,12,0.12)',
    accentColor: '#EA580C',
    live: true,
  },
  {
    id: 'consultant-payout',
    section: 'today',
    filterCategory: 'payouts',
    title: 'Payout Credited',
    body: 'Your earnings of $120 for last week have been credited.',
    timeLabel: '4h ago',
    icon: 'wallet-outline',
    iconColor: '#0D9488',
    iconBgColor: 'rgba(13,148,136,0.12)',
    accentColor: '#0D9488',
  },
  {
    id: 'consultant-session-done',
    section: 'yesterday',
    filterCategory: 'bookings',
    title: 'Session Completed',
    body: 'Session with Maria marked as completed. Payout pending.',
    timeLabel: '24h ago',
    icon: 'checkmark-done-outline',
    iconColor: '#64748B',
    iconBgColor: 'rgba(100,116,139,0.12)',
  },
  {
    id: 'consultant-cancelled',
    section: 'yesterday',
    filterCategory: 'bookings',
    title: 'User Cancelled',
    body: 'Booking with John for 3:00 PM was cancelled by the user.',
    timeLabel: 'Yesterday',
    icon: 'close-circle-outline',
    iconColor: '#EF4444',
    iconBgColor: 'rgba(239,68,68,0.12)',
  },
  {
    id: 'consultant-profile-approved',
    section: 'earlier',
    filterCategory: 'general',
    title: 'Profile Approved',
    body: 'Your updated profile details have been approved.',
    timeLabel: 'Oct 12',
    icon: 'shield-checkmark-outline',
    iconColor: '#2563EB',
    iconBgColor: 'rgba(37,99,235,0.10)',
  },
];
