import type { NotificationItem } from '../types/notifications.types';

export const USER_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'user-booking-confirmed',
    section: 'today',
    filterCategory: 'bookings',
    title: 'Booking Confirmed',
    body: 'Your session with Dr. Smith is confirmed for tomorrow at 10 AM.',
    timeLabel: '10:45 AM',
    icon: 'calendar-outline',
    iconColor: '#0D9488',
    iconBgColor: 'rgba(13,148,136,0.12)',
    accentColor: '#0D9488',
    unread: true,
  },
  {
    id: 'user-incoming-call',
    section: 'today',
    filterCategory: 'bookings',
    title: 'Incoming Call',
    body: 'You have an incoming video call.',
    timeLabel: 'Now',
    icon: 'videocam-outline',
    iconColor: '#0D9488',
    iconBgColor: 'rgba(13,148,136,0.12)',
    accentColor: '#0D9488',
    unread: true,
    showActions: true,
    actionTone: 'teal',
  },
  {
    id: 'user-payment-success',
    section: 'today',
    filterCategory: 'payments',
    title: 'Payment Success',
    body: "Payment of $50 for 'Workshop: AI Basics' was successful.",
    timeLabel: '2h ago',
    icon: 'checkmark-circle-outline',
    iconColor: '#0D9488',
    iconBgColor: 'rgba(13,148,136,0.12)',
  },
  {
    id: 'user-missed-call',
    section: 'yesterday',
    filterCategory: 'bookings',
    title: 'Missed Call',
    body: 'You missed a call from Consultant Sarah.',
    timeLabel: '4:20 PM',
    icon: 'call-outline',
    iconColor: '#EA580C',
    iconBgColor: 'rgba(234,88,12,0.12)',
    accentColor: '#EA580C',
    unread: true,
  },
  {
    id: 'user-workshop-reminder',
    section: 'yesterday',
    filterCategory: 'bookings',
    title: 'Workshop Reminder',
    body: "Don't forget! Your 'Career Growth' workshop starts in 1 hour.",
    timeLabel: '10:00 AM',
    icon: 'alarm-outline',
    iconColor: '#EA580C',
    iconBgColor: 'rgba(234,88,12,0.12)',
  },
  {
    id: 'user-refund',
    section: 'earlier',
    filterCategory: 'payments',
    title: 'Refund Completed',
    body: 'Refund for cancelled booking #123 has been processed.',
    timeLabel: 'Oct 24',
    icon: 'cash-outline',
    iconColor: '#64748B',
    iconBgColor: 'rgba(100,116,139,0.12)',
  },
];
