import {  StyleSheet, } from 'react-native';
import { THEME } from '@/constants/theme';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  missWrap: {
    flex: 1,
    justifyContent: 'center',
  },
  scrollContent: {
    paddingBottom: THEME.spacing[24],
    gap: THEME.spacing[20],
  },
  heroWrap: {
    paddingHorizontal: THEME.spacing[0],
    // marginTop: THEME.spacing[8],
  },
  heroBg: {
    // borderRadius: 22,
    padding: THEME.spacing[16],
    gap: THEME.spacing[12],
    height: 392,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    overflow: 'hidden',
  },
  heroDecor: {
    ...StyleSheet.absoluteFill,
  },
  heroGlowA: {
    position: 'absolute',
    right: -80,
    top: -60,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  heroGlowB: {
    position: 'absolute',
    left: -70,
    // bottom: -90,
    width: 260,
    // height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(14,165,233,0.18)',
    bottom: -90,
    height: 260,
  },
  heroGlowC: {
    position: 'absolute',
    left: 60,
    top: 70,
    width: 140,
    height: 140,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: THEME.spacing[12],
  },
  badgesRow: {
    width: '90%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    // gap: THEME.spacing[8],
    justifyContent: "space-between",
  },
  pillLight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
    backgroundColor: 'rgba(255,255,255,0.88)',
    paddingHorizontal: THEME.spacing[12],
    paddingVertical: THEME.spacing[8],
    borderRadius: 999,
    maxWidth: '100%',
  },
  pillLightText: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
  },
  dealChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
    backgroundColor: 'rgba(0,0,0,0.18)',
    paddingHorizontal: THEME.spacing[12],
    paddingVertical: THEME.spacing[8],
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  dealChipText: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.white,
    letterSpacing: 0.2,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.white,
    letterSpacing: -0.4,
    lineHeight: 28,
  },
  heroSummary: {
    fontSize: THEME.typography.size[14],
    color: 'rgba(255,255,255,0.88)',
    lineHeight: 20,
  },
  trustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
    marginTop: 2,
  },
  trustItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  trustDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.55)',
  },
  trustText: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.white,
  },
  trustTextMuted: {
    fontSize: THEME.typography.size[12],
    color: 'rgba(255,255,255,0.80)',
  },
  heroCard: {
    backgroundColor: THEME.colors.white,
    borderRadius: 18,
    padding: THEME.spacing[14],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: THEME.spacing[12],
    shadowColor: THEME.colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
    width: '92%',
    

  },
  heroCardLeft: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  priceLabel: {
    fontSize: 18,
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
    letterSpacing: -0.2,
  },
  subLabel: {
    fontSize: THEME.typography.size[12],
    color: THEME.colors.textSecondary,
  },
  heroCta: {
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: THEME.spacing[8],
    backgroundColor: THEME.colors.accentAmber,
    borderRadius: 999,
    paddingHorizontal: THEME.spacing[12],
    height: 40,
  },
  heroCtaPressed: {
    opacity: 0.9,
  },
  heroCtaText: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.white,
  },
  quickActions: {
    flexDirection: 'row',
    gap: THEME.spacing[12],
    marginTop: 2,
  },
  quickBtn: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: THEME.spacing[8],
    backgroundColor: 'rgba(0,0,0,0.20)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  quickPressed: {
    opacity: 0.9,
  },
  quickBtnText: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.white,
  },
  highlights: {
    paddingHorizontal: THEME.spacing[16],
    gap: THEME.spacing[12],
  },
  highlightsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  highlightsTitle: {
    fontSize: THEME.typography.size[18],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
  },
  highlightsList: {
    gap: THEME.spacing[12],
  },
  highlightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[12],
    padding: THEME.spacing[12],
    borderRadius: 16,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    backgroundColor: THEME.colors.white,
  },
  highlightIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: `${THEME.colors.accentAmber}12`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  highlightTitle: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textPrimary,
  },
  highlightSubtitle: {
    fontSize: THEME.typography.size[12],
    color: THEME.colors.textSecondary,
  },
  tabs: {
    paddingHorizontal: THEME.spacing[16],
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  tab: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: THEME.colors.border,
    backgroundColor: THEME.colors.white,
    paddingHorizontal: THEME.spacing[12],

  },
  tabActive: {
    backgroundColor: THEME.colors.black,
    borderColor: THEME.colors.black,
  },
  tabPressed: {
    opacity: 0.9,
  },
  tabText: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textSecondary,
  },
  tabTextActive: {
    color: THEME.colors.white,
  },
  section: {
    paddingHorizontal: THEME.spacing[16],
    gap: THEME.spacing[8],
  },
  sectionLast: {
    paddingHorizontal: THEME.spacing[16],
    gap: THEME.spacing[8],
    marginBottom: THEME.spacing[8],
  },
  body: {
    fontSize: THEME.typography.size[16],
    lineHeight: 24,
    color: THEME.colors.textSecondary,
  },
  bulletList: {
    gap: THEME.spacing[8],
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing[8],
  },
  bulletMark: {
    fontSize: THEME.typography.size[16],
    color: THEME.colors.textPrimary,
    lineHeight: 24,
    marginTop: 0,
  },
  bulletText: {
    flex: 1,
    fontSize: THEME.typography.size[16],
    lineHeight: 24,
    color: THEME.colors.textSecondary,
  },
});