export const ROUTES = {
  Root: {
    Auth: 'Root/Auth',
    App: 'Root/App',
    /** Full-screen stack above tabs (not a tab bar destination). */
    ConsultantsList: 'Root/ConsultantsList',
    ConsultantDetail: 'Root/ConsultantDetail',
    Wallet: 'Root/Wallet',
    WorkshopsList: 'Root/WorkshopsList',
     WorkshopsDetail: 'Root/WorkshopDetailsScreen',
    ConsultationOnboarding: 'Root/ConsultationOnboarding',
    IncomingCall: 'Root/IncomingCall',
    OutgoingCall: 'Root/OutgoingCall',
    InCall: 'Root/InCall',
    Search: 'Root/Search',
    BizAI: 'Root/BizAI',
  },
  Auth: {
    Splash: 'Auth/Splash',
    Landing: 'Auth/Landing',
    ChooseAccountType: 'Auth/ChooseAccountType',
    Login: 'Auth/Login',
    Signup: 'Auth/Signup',
    OtpVerification: 'Auth/OtpVerification',
    ProfileSetup: 'Auth/ProfileSetup',
  },
  App: {
    Home: 'App/Home',
    Services: 'App/Services',
    Edp: 'App/Edp',
    Account: 'App/Account',
  },
  Edp: {
    Main: 'Edp/Main',
    Modules: 'Edp/Modules',
    ModuleDetail: 'Edp/ModuleDetail',
  },
  Services: {
    List: 'App/Services/List',
    Detail: 'App/Services/Detail',
    Onboarding: 'App/Services/Onboarding',
  },
  Account: {
    Home: 'App/Account/Home',
    HelpSettings: 'App/Account/HelpSettings',
    Membership: 'App/Account/MembershipScreen',
    EditProfile: 'App/Account/EditProfile',
    ConsultantBankDetailsScreen: 'App/Account/ConsultantBankDetailsScreen',
    ExpertVideosScreen: 'App/Account/ExpertVideosScreen',
        TransactionHis: 'App/Account/TransactionHistory',
        CreditsScreen: 'App/Account/CreditsScreen',
        addReview: 'App/Account/AddReviewScreen',
        userGuide: 'App/Account/UserGuideScreen',
        userCallHis: 'App/Account/CallHistoryScreen',
  },
} as const;

