import { Platform, StyleSheet } from 'react-native';

import { THEME } from '@/constants/theme';

export const CONSULTANT_ACCENT = THEME.colors.primary;
export const CONSULTANT_ACCENT_SOFT = 'rgba(15,81,50,0.10)';
export const CONSULTANT_CANVAS = '#F4F8F6';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: CONSULTANT_CANVAS,
  },
  scrollContent: {
    paddingBottom: THEME.spacing[24],
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: THEME.spacing[12],
    paddingVertical: THEME.spacing[10],
    backgroundColor: THEME.colors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: THEME.colors.border,
  },
  pageTitle: {
    fontSize: THEME.typography.size[18],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
    letterSpacing: -0.25,
  },
  settingsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[4],
    paddingHorizontal: THEME.spacing[10],
    paddingVertical: THEME.spacing[8],
    borderRadius: THEME.radius[12],
    backgroundColor: CONSULTANT_ACCENT_SOFT,
    borderWidth: 1,
    borderColor: 'rgba(15,81,50,0.16)',
  },
  settingsBtnText: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.bold as '700',
    color: CONSULTANT_ACCENT,
    letterSpacing: 0.15,
  },
  subscriptionCard: {
    marginHorizontal: THEME.spacing[12],
    marginTop: THEME.spacing[10],
    borderRadius: THEME.radius[16],
    overflow: 'hidden',
    backgroundColor: THEME.colors.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: THEME.colors.border,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  subscriptionShimmer: {
    height: 2,
    backgroundColor: CONSULTANT_ACCENT,
    opacity: 0.35,
  },
  subscriptionInner: {
    padding: THEME.spacing[14],
    gap: THEME.spacing[10],
  },
  subscriptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: THEME.spacing[10],
  },
  subscriptionLeft: {
    flex: 1,
    minWidth: 0,
    gap: THEME.spacing[4],
  },
  subscriptionPlanRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  subscriptionPlanText: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.bold as '700',
    color: CONSULTANT_ACCENT,
    letterSpacing: -0.15,
  },
  subscriptionChevron: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.bold as '700',
    color: CONSULTANT_ACCENT,
  },
  subscriptionPhone: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textSecondary,
  },
  upgradeBtn: {
    paddingHorizontal: THEME.spacing[14],
    paddingVertical: THEME.spacing[8],
    borderRadius: THEME.radius[12],
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  upgradeBtnText: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
    letterSpacing: 0.2,
  },
  section: {
    marginTop: THEME.spacing[14],
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: THEME.spacing[12],
    marginBottom: THEME.spacing[8],
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: THEME.spacing[12],
    marginBottom: THEME.spacing[8],
    gap: THEME.spacing[8],
  },
  sectionHeaderTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
    letterSpacing: -0.2,
  },
  sectionLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth * 2,
    backgroundColor: 'rgba(15,23,42,0.1)',
    marginLeft: THEME.spacing[10],
    borderRadius: 1,
  },
  editRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[4],
    paddingHorizontal: THEME.spacing[8],
    paddingVertical: THEME.spacing[4],
    borderRadius: THEME.radius[8],
    backgroundColor: CONSULTANT_ACCENT_SOFT,
  },
  editText: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.bold as '700',
    color: CONSULTANT_ACCENT,
  },
  profilesPanel: {
    marginHorizontal: THEME.spacing[12],
    paddingVertical: THEME.spacing[14],
    paddingHorizontal: THEME.spacing[12],
    borderRadius: THEME.radius[16],
    backgroundColor: THEME.colors.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: THEME.colors.border,
  },
  profilesRow: {
    flexDirection: 'row',
    gap: THEME.spacing[20],
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  profileItem: {
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  profileAvatarRing: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(15,81,50,0.22)',
  },
  profileAvatarInner: {
    flex: 1,
    backgroundColor: '#0B3D2C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileEmoji: {
    fontSize: 28,
  },
  profileKidsBadge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: CONSULTANT_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(15,81,50,0.3)',
  },
  profileKidsText: {
    color: THEME.colors.white,
    fontSize: 10,
    fontWeight: THEME.typography.weight.bold as '700',
    letterSpacing: 0.6,
  },
  addProfileCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: 'rgba(15,81,50,0.35)',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CONSULTANT_ACCENT_SOFT,
  },
  addProfilePlus: {
    fontSize: THEME.typography.size[24],
    color: CONSULTANT_ACCENT,
    lineHeight: 28,
    fontWeight: THEME.typography.weight.bold as '700',
  },
  profileName: {
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textSecondary,
    textAlign: 'center',
  },
  notificationCard: {
    marginHorizontal: THEME.spacing[12],
    borderRadius: THEME.radius[16],
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15,81,50,0.14)',
    backgroundColor: THEME.colors.white,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  notificationShimmer: {
    height: 2,
    backgroundColor: CONSULTANT_ACCENT,
    opacity: 0.3,
  },
  notificationInner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: THEME.spacing[12],
  },
  videoThumbnail: {
    width: 88,
    height: 60,
    borderRadius: THEME.radius[12],
    backgroundColor: THEME.colors.surface,
  },
  notificationContent: {
    flex: 1,
    marginLeft: THEME.spacing[12],
    justifyContent: 'center',
    minWidth: 0,
  },
  videoTitle: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
    letterSpacing: -0.15,
  },
  videoDescription: {
    marginTop: THEME.spacing[4],
    fontSize: THEME.typography.size[12],
    lineHeight: 16,
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textSecondary,
  },
  arrowBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: CONSULTANT_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: THEME.spacing[8],
  },
  watchRow: {
    flexDirection: 'row',
    gap: THEME.spacing[10],
    paddingHorizontal: THEME.spacing[12],
    marginBottom: THEME.spacing[10],
  },
  watchCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: THEME.radius[16],
    overflow: 'hidden',
    backgroundColor: THEME.colors.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: THEME.colors.border,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  watchCardSpacer: {
    flex: 1,
    minWidth: 0,
  },
  watchThumbnail: {
    width: '100%',
    aspectRatio: 16 / 9,
    justifyContent: 'flex-end',
    backgroundColor: '#111827',
  },
  watchThumbnailImage: {
    borderTopLeftRadius: THEME.radius[16],
    borderTopRightRadius: THEME.radius[16],
  },
  watchThumbnailOverlay: {
    ...StyleSheet.absoluteFill,
  },
  watchPlayOverlay: {
    position: 'absolute',
    bottom: THEME.spacing[8],
    left: THEME.spacing[8],
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  watchProgressTrack: {
    height: 3,
    backgroundColor: THEME.colors.surface,
  },
  watchProgressFill: {
    height: 3,
    backgroundColor: CONSULTANT_ACCENT,
    borderRadius: 2,
  },
  watchCardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: THEME.spacing[10],
    paddingVertical: THEME.spacing[10],
    gap: THEME.spacing[8],
  },
  watchCardTitle: {
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.bold as '700',
    color: THEME.colors.textPrimary,
    letterSpacing: -0.15,
  },
  watchCardSubLabel: {
    marginTop: 3,
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.semibold as '600',
    color: THEME.colors.textSecondary,
  },
  watchMoreBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CONSULTANT_ACCENT_SOFT,
  },
});
