import { THEME } from '@/constants/theme';
import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.colors.background,
  },
  content: {
    paddingBottom: 100, // For bottom nav
  },

  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    color: THEME.colors.textPrimary,
    fontSize: THEME.typography.size[18],
    fontWeight: THEME.typography.weight.semibold as any,
  },
  profileContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    padding: 2,
  },
  profileImage: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
    backgroundColor: THEME.colors.border, // Placeholder
  },
  balanceCard: {
  marginHorizontal: THEME.spacing[20],
  backgroundColor: '#F8FAFC',
  borderRadius: 20,
  padding: THEME.spacing[16],
  gap: THEME.spacing[10],
  borderWidth: 1,
  borderColor: '#E2E8F0',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.06,
  shadowRadius: 10,
  elevation: 4,
  overflow: 'hidden',
},
  balanceLabel: {
    color: THEME.colors.textSecondary,
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.medium as any,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  balanceValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: THEME.spacing[8],
  },
  balanceValue: {
    color: THEME.colors.textPrimary,
    fontSize: 32,
    fontWeight: THEME.typography.weight.bold as any,
  },
  balanceUnit: {
    color: THEME.colors.textSecondary,
    fontSize: THEME.typography.size[16],
  },
 refreshButton: {
  position: 'absolute',
  right: THEME.spacing[16],
  top: THEME.spacing[16],
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#FFFFFF',
  paddingHorizontal: THEME.spacing[12],
  paddingVertical: THEME.spacing[8],
  borderRadius: 20,
  gap: THEME.spacing[4],
  borderWidth: 1,
  borderColor: '#E2E8F0',
},
refreshText: {
  color: '#0F172A',
  fontSize: THEME.typography.size[12],
  fontWeight: THEME.typography.weight.medium as any,
},
  walletSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: THEME.spacing[20],
    marginTop: THEME.spacing[16],
  },
  walletIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletInfo: {
    flex: 1,
    marginLeft: THEME.spacing[12],
  },
  walletTitle: {
    color: THEME.colors.textPrimary,
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.bold as any,
  },
  walletSubtitle: {
    color: THEME.colors.textSecondary,
    fontSize: 10,
  },
  walletBalance: {
    alignItems: 'flex-end',
  },
  walletAmount: {
    color: THEME.colors.textPrimary,
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.bold as any,
  },
  topUpLink: {
    color: THEME.colors.accentBlue,
    fontSize: THEME.typography.size[12],
    textDecorationLine: 'underline',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: THEME.spacing[20],
    marginTop: THEME.spacing[24],
    marginBottom: THEME.spacing[16],
    gap: THEME.spacing[12],
  },
  headerAccent: {
    width: 4,
    height: 22,
    borderRadius: 2,
    backgroundColor: THEME.colors.accentAmber,
  },
  sectionTitle: {
    color: THEME.colors.textPrimary,
    fontSize: THEME.typography.size[20],
    fontWeight: THEME.typography.weight.bold as any,
    letterSpacing: -0.4,
  },
  countBadge: {
    backgroundColor: 'rgba(65, 47, 15, 0.18)',
    paddingHorizontal: THEME.spacing[8],
    paddingVertical: 2,
    borderRadius: 10,
  },
  countText: {
    color: THEME.colors.accentAmber,
    fontSize: THEME.typography.size[12],
    fontWeight: THEME.typography.weight.bold as any,
  },
  packCard: {
    marginHorizontal: THEME.spacing[20],
    borderRadius: 20,
    padding: THEME.spacing[16],
    gap: THEME.spacing[10],
    marginBottom: THEME.spacing[16],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 8,
    overflow: 'hidden',
  },
  shimmerLine: {
    height: 1,
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
  },
  packHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  packTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  packTitle: {
    color: THEME.colors.textPrimary,
    fontSize: THEME.typography.size[18],
    fontWeight: THEME.typography.weight.bold as any,
  },
  statusBadge: {
    paddingHorizontal: THEME.spacing[8],
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
  },
  statusText: {
    fontSize: 10,
    fontWeight: THEME.typography.weight.bold as any,
  },
  packDescription: {
    color: THEME.colors.textSecondary,
    fontSize: THEME.typography.size[14],
  },
  packPriceContainer: {
    alignItems: 'flex-end',
  },
  packPrice: {
    color: THEME.colors.textPrimary,
    fontSize: THEME.typography.size[18],
    fontWeight: THEME.typography.weight.bold as any,
  },
  packPriceUnit: {
    color: THEME.colors.textSecondary,
    fontSize: 10,
    textTransform: 'uppercase',
    fontWeight: THEME.typography.weight.bold as any,
  },
  actionContainer: {
    marginTop: THEME.spacing[8],
    gap: THEME.spacing[10],
  },
  primaryButton: {
    backgroundColor: THEME.colors.white,
    height: 48,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  primaryButtonText: {
    color: THEME.colors.black,
    fontSize: THEME.typography.size[14],
    fontWeight: THEME.typography.weight.semibold as any,
  },
secondaryButton: {
  backgroundColor: '#FFFFFF',
  height: 48,
  borderRadius: 16,
  flexDirection: 'row',
  justifyContent: 'center',
  alignItems: 'center',
  gap: THEME.spacing[8],
  borderWidth: 1,
  borderColor: '#E2E8F0',
},
secondaryButtonText: {
  color: '#0F172A',
  fontSize: THEME.typography.size[14],
  fontWeight: THEME.typography.weight.semibold as any,
},
  insufficientTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[4],
    marginTop: THEME.spacing[4],
  },
  insufficientText: {
    color: '#EF4444',
    fontSize: THEME.typography.size[12],
    lineHeight: 16,
  },
  footer: {
    alignItems: 'center',
    marginTop: THEME.spacing[32],
    paddingBottom: 40,
  },
  footerText: {
    color: THEME.colors.textSecondary,
    fontSize: THEME.typography.size[14],
  },
  contactButton: {
    marginTop: THEME.spacing[8],
    borderBottomWidth: 2,
    borderBottomColor: THEME.colors.textPrimary,
    paddingBottom: THEME.spacing[4],
  },
  contactButtonText: {
    color: THEME.colors.black,
    fontSize: THEME.typography.size[16],
    fontWeight: THEME.typography.weight.bold as any,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 80,
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    paddingBottom: 10,
  },
  navItem: {
    alignItems: 'center',
    gap: THEME.spacing[4],
  },
  navLabel: {
    fontSize: 10,
    fontWeight: THEME.typography.weight.bold as any,
    textTransform: 'uppercase',
    letterSpacing: -0.5,
  },
  iconContainer: {
    width: 52,
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconInner: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
