import { StyleSheet } from 'react-native';

import { THEME } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: THEME.colors.background,
  },
  scrollContent: {
    paddingHorizontal: THEME.spacing[16],
    paddingTop: THEME.spacing[8],
    paddingBottom: 112,
    gap: THEME.spacing[16],
  },
  intro: {
    marginBottom: THEME.spacing[4],
  },
  pageTitle: {
    fontSize: THEME.typography.size[22],
    fontWeight: '700',
    color: THEME.colors.textPrimary,
    lineHeight: 28,
  },
  pageSubtitle: {
    marginTop: THEME.spacing[8],
    fontSize: THEME.typography.size[14],
    color: THEME.colors.textSecondary,
    lineHeight: 20,
  },
  planCard: {
    borderRadius: 18,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 5,
  },
  planCardSelected: {
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 8,
  },
  cardBlob: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 96,
    height: 76,
    borderBottomLeftRadius: 56,
    borderTopRightRadius: 18,
    opacity: 0.2,
  },
  planHeaderTrailing: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[8],
  },
  selectedCheckInline: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planCardBody: {
    padding: THEME.spacing[16],
  },
  planHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: THEME.spacing[12],
  },
  planTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: THEME.spacing[6],
    marginBottom: THEME.spacing[8],
  },
  badge: {
    paddingHorizontal: THEME.spacing[10],
    paddingVertical: 4,
    borderRadius: 999,
  },
  badgeText: {
    fontSize: THEME.typography.size[11],
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  popularBadge: {
    paddingHorizontal: THEME.spacing[10],
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
  },
  popularBadgeText: {
    fontSize: THEME.typography.size[11],
    fontWeight: '700',
    color: '#B45309',
    textTransform: 'uppercase',
  },
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planName: {
    fontSize: THEME.typography.size[20],
    fontWeight: '700',
    color: THEME.colors.textPrimary,
  },
  planDescription: {
    marginTop: 4,
    fontSize: THEME.typography.size[13],
    color: THEME.colors.textSecondary,
    lineHeight: 18,
  },
  priceRow: {
    marginTop: THEME.spacing[14],
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: THEME.spacing[8],
  },
  priceAmount: {
    fontSize: THEME.typography.size[28],
    fontWeight: '800',
    color: THEME.colors.textPrimary,
    letterSpacing: -0.5,
  },
  priceStrike: {
    fontSize: THEME.typography.size[14],
    color: THEME.colors.textSecondary,
    textDecorationLine: 'line-through',
    marginBottom: 4,
  },
  metaText: {
    marginTop: THEME.spacing[6],
    fontSize: THEME.typography.size[13],
    color: THEME.colors.textSecondary,
    lineHeight: 18,
  },
  walletText: {
    marginTop: THEME.spacing[4],
    fontSize: THEME.typography.size[13],
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: THEME.colors.border,
    marginVertical: THEME.spacing[16],
  },
  sectionTitle: {
    fontSize: THEME.typography.size[13],
    fontWeight: '700',
    color: THEME.colors.textPrimary,
    marginBottom: THEME.spacing[10],
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  scopeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing[10],
    marginBottom: THEME.spacing[10],
  },
  scopeTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  scopeTitle: {
    fontSize: THEME.typography.size[14],
    color: THEME.colors.textPrimary,
    lineHeight: 20,
  },
  scopeAmount: {
    fontSize: THEME.typography.size[12],
    fontWeight: '600',
    color: THEME.colors.textSecondary,
    marginTop: 2,
  },
  termsToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: THEME.spacing[4],
  },
  termsToggleText: {
    fontSize: THEME.typography.size[14],
    fontWeight: '600',
    color: THEME.colors.textPrimary,
  },
  termsList: {
    marginTop: THEME.spacing[8],
    gap: THEME.spacing[8],
  },
  termItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing[8],
  },
  termBullet: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: THEME.colors.textSecondary,
    marginTop: 7,
  },
  termText: {
    flex: 1,
    fontSize: THEME.typography.size[12],
    color: THEME.colors.textSecondary,
    lineHeight: 18,
  },
  stickyFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: THEME.spacing[16],
    paddingTop: THEME.spacing[12],
    paddingBottom: THEME.spacing[16],
    borderTopWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: THEME.spacing[12],
  },
  stickyPriceGroup: {
    flex: 1,
    minWidth: 0,
  },
  stickyTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing[6],
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  stickyBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  stickyBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  stickyPlanName: {
    fontSize: THEME.typography.size[13],
    fontWeight: '700',
    flexShrink: 1,
  },
  stickyPrice: {
    fontSize: THEME.typography.size[22],
    fontWeight: '800',
    color: THEME.colors.textPrimary,
    marginTop: 2,
  },
  stickyMeta: {
    fontSize: THEME.typography.size[12],
    color: THEME.colors.textSecondary,
    marginTop: 2,
  },
  upgradeCta: {
    paddingHorizontal: THEME.spacing[20],
    paddingVertical: THEME.spacing[14],
    borderRadius: 12,
    minWidth: 140,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  upgradeCtaText: {
    fontSize: THEME.typography.size[15],
    fontWeight: '700',
    color: THEME.colors.white,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: THEME.spacing[24],
  },
  errorText: {
    fontSize: THEME.typography.size[14],
    color: THEME.colors.textSecondary,
    textAlign: 'center',
    marginBottom: THEME.spacing[12],
  },
  retryButton: {
    paddingHorizontal: THEME.spacing[16],
    paddingVertical: THEME.spacing[10],
    borderRadius: 10,
    backgroundColor: THEME.colors.primary,
  },
  retryText: {
    color: THEME.colors.white,
    fontWeight: '600',
  },
});
